version: 2

project_name: instrument-server

before:
  hooks:
    - go mod tidy
    - go test ./...

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: instrument-server-app
    main: ./cmd/server
    binary: instrument-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{ .Os }}_
      {{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - src: "dist/CHANGELOG.md"
        dst: "."
        strip_parent: true

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  abbrev: 0
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Documentation"
      regexp: '^.*?docs?(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Others"
      order: 999

release:
  github:
    owner: liultimate
    name: instrument-server
  draft: false
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  prerelease: auto
  mode: append
  name_template: "{{ .ProjectName }} v{{ .Version }}"
  header: |
    ## 🎉 Release {{ .Version }}
    
    ### Installation
    
    Download the appropriate binary for your platform below.
    
  footer: |
    ---
    
    ### Checksums
    
    Verify your download:
    ```bash
    sha256sum -c {{ .ProjectName }}_{{ .Version }}_checksums.txt
